sudo: true
dist: trusty
language: node_js
node_js: stable

addons:
  sauce_connect: true

cache:
  directories:
    - node_modules

addons:
  google-chrome: latest

install:
  - npm install

script:
  - npm run test
